# This file defines the different types of taxonomies in Bolt. See the 
# documentation for details: http://docs.bolt.cm/taxonomies#taxonomies

tags:
    slug: tags
    singular_slug: tag
    behaves_like: tags

exams:
    name: Exams
    slug: exams
    singular_name: Exam
    singular_slug: exam
    behaves_like: categories
    multiple: false
    options: [ KET, PET, First, Advanced, Proficiency ]
